name: CI

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Install Dependencies
        run: npm install

      - name: Linting
        run: |
          npm run lint
          npx stylelint "**/*.{css,scss}"
        allow_failure: true

      - name: Build
        run: npm run build

      - name: Test
        run: npm test
